### ISSUE TITLE
Doesn't work with PHPSpec 3.0

### ISSUE THREAD

**Issue by Dragonrun1** [phpspec/nyan-formatters#7]
May just need composer.json update. Don't think anything should have broke but you probably know better than me ;)

**Comment by mdavis1982** [comment]
@Dragonrun1 I've just prepared a branch that will hopefully ensure PhpSpec 3.0 compatibility. Just waiting on review and comment before it can be merged.

See #8 

Cheers

**Comment by mdavis1982** [comment]
@Dragonrun1 I've now tagged `2.0` so you should be able to use the extension in PhpSpec 3.0

**Comment by Dragonrun1** [comment]
TY I'll check it out. I was starting to go into kitty withdrawal and it's not pretty 😉
